CREATE DATABASE [tokanpages-dev]
    CONTAINMENT = NONE
    ON PRIMARY (
        NAME = N'tokanpages-dev_Data', 
        FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLE2022\MSSQL\DATA\tokanpages-dev.mdf', 
        SIZE = 21504KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024KB
    )
    LOG ON ( 
        NAME = N'tokanpages-dev_Log',
        FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLE2022\MSSQL\DATA\tokanpages-dev.ldf', 
        SIZE = 28608KB, 
        MAXSIZE = 2048GB, 
        FILEGROWTH = 10%
    )
    WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

ALTER DATABASE [tokanpages-dev] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [tokanpages-dev].[dbo].[sp_fulltext_database] @action = 'enable'
END

GO
ALTER DATABASE [tokanpages-dev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tokanpages-dev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tokanpages-dev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tokanpages-dev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tokanpages-dev] SET ARITHABORT OFF 
GO
ALTER DATABASE [tokanpages-dev] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [tokanpages-dev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tokanpages-dev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tokanpages-dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tokanpages-dev] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tokanpages-dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tokanpages-dev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tokanpages-dev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tokanpages-dev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tokanpages-dev] SET  DISABLE_BROKER 
GO
ALTER DATABASE [tokanpages-dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tokanpages-dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tokanpages-dev] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [tokanpages-dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [tokanpages-dev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tokanpages-dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [tokanpages-dev] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [tokanpages-dev] SET RECOVERY FULL 
GO
ALTER DATABASE [tokanpages-dev] SET  MULTI_USER 
GO
ALTER DATABASE [tokanpages-dev] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [tokanpages-dev] SET DB_CHAINING OFF 
GO
ALTER DATABASE [tokanpages-dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [tokanpages-dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [tokanpages-dev] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [tokanpages-dev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [tokanpages-dev] SET QUERY_STORE = ON
GO
ALTER DATABASE [tokanpages-dev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)

