//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokanPages.Backend.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TokanPages.Backend.Shared.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        public static string ARTICLE_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ARTICLE_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string CANNOT_SAVE_TO_AZURE_STORAGE {
            get {
                return ResourceManager.GetString("CANNOT_SAVE_TO_AZURE_STORAGE", resourceCulture);
            }
        }
        
        public static string EMAIL_ADDRESS_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string ERROR_UNEXPECTED {
            get {
                return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture);
            }
        }
        
        public static string INVALID_BASE64 {
            get {
                return ResourceManager.GetString("INVALID_BASE64", resourceCulture);
            }
        }
        
        public static string SUBSCRIBER_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("SUBSCRIBER_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string USER_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USER_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string CANNOT_SEND_EMAIL {
            get {
                return ResourceManager.GetString("CANNOT_SEND_EMAIL", resourceCulture);
            }
        }
        
        public static string CANNOT_CONNECT_DATABASE {
            get {
                return ResourceManager.GetString("CANNOT_CONNECT_DATABASE", resourceCulture);
            }
        }
        
        public static string NOT_CONNECTED_TO_SMTP {
            get {
                return ResourceManager.GetString("NOT_CONNECTED_TO_SMTP", resourceCulture);
            }
        }
        
        public static string NOT_AUTHENTICATED_WITH_SMTP {
            get {
                return ResourceManager.GetString("NOT_AUTHENTICATED_WITH_SMTP", resourceCulture);
            }
        }
        
        public static string SMTP_CLIENT_ERROR {
            get {
                return ResourceManager.GetString("SMTP_CLIENT_ERROR", resourceCulture);
            }
        }
        
        public static string ARGUMENT_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ARGUMENT_NULL_EXCEPTION", resourceCulture);
            }
        }
    }
}
