//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokanPages.Backend.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TokanPages.Backend.Shared.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        public static string ARTICLE_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ARTICLE_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string CANNOT_SAVE_TO_AZURE_STORAGE {
            get {
                return ResourceManager.GetString("CANNOT_SAVE_TO_AZURE_STORAGE", resourceCulture);
            }
        }
        
        public static string EMAIL_ADDRESS_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string ERROR_UNEXPECTED {
            get {
                return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture);
            }
        }
        
        public static string SUBSCRIBER_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("SUBSCRIBER_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string USER_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USER_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string CANNOT_SEND_EMAIL {
            get {
                return ResourceManager.GetString("CANNOT_SEND_EMAIL", resourceCulture);
            }
        }
        
        public static string CANNOT_CONNECT_DATABASE {
            get {
                return ResourceManager.GetString("CANNOT_CONNECT_DATABASE", resourceCulture);
            }
        }
        
        public static string USER_ACCOUNT_INACTIVE {
            get {
                return ResourceManager.GetString("USER_ACCOUNT_INACTIVE", resourceCulture);
            }
        }
        
        public static string EXPIRED_RESET_ID {
            get {
                return ResourceManager.GetString("EXPIRED_RESET_ID", resourceCulture);
            }
        }
        
        public static string EXPIRED_ACTIVATION_ID {
            get {
                return ResourceManager.GetString("EXPIRED_ACTIVATION_ID", resourceCulture);
            }
        }
        
        public static string COMPONENT_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("COMPONENT_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        public static string COMPONENT_NAME_UNKNOWN {
            get {
                return ResourceManager.GetString("COMPONENT_NAME_UNKNOWN", resourceCulture);
            }
        }
        
        public static string COMPONENT_CONTENT_EMPTY {
            get {
                return ResourceManager.GetString("COMPONENT_CONTENT_EMPTY", resourceCulture);
            }
        }
        
        public static string COMPONENT_CONTENT_MISSING_TOKEN {
            get {
                return ResourceManager.GetString("COMPONENT_CONTENT_MISSING_TOKEN", resourceCulture);
            }
        }
        
        public static string EMAIL_TEMPLATE_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_TEMPLATE_EMPTY", resourceCulture);
            }
        }
        
        public static string COMPONENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMPONENT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string REVOKED_USER_TOKEN {
            get {
                return ResourceManager.GetString("REVOKED_USER_TOKEN", resourceCulture);
            }
        }
        
        public static string ARGUMENT_EMPTY_OR_NULL {
            get {
                return ResourceManager.GetString("ARGUMENT_EMPTY_OR_NULL", resourceCulture);
            }
        }
        
        public static string ASSET_NOT_FOUND {
            get {
                return ResourceManager.GetString("ASSET_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string CANNOT_READ_FROM_AZURE_STORAGE {
            get {
                return ResourceManager.GetString("CANNOT_READ_FROM_AZURE_STORAGE", resourceCulture);
            }
        }
        
        public static string ASSET_CONTENT_TYPE_MISSING {
            get {
                return ResourceManager.GetString("ASSET_CONTENT_TYPE_MISSING", resourceCulture);
            }
        }
        
        public static string HTTP_REQUEST_FAILED {
            get {
                return ResourceManager.GetString("HTTP_REQUEST_FAILED", resourceCulture);
            }
        }
        
        public static string CANNOT_PARSE {
            get {
                return ResourceManager.GetString("CANNOT_PARSE", resourceCulture);
            }
        }
        
        public static string BUS_MESSAGE_TOO_LARGE {
            get {
                return ResourceManager.GetString("BUS_MESSAGE_TOO_LARGE", resourceCulture);
            }
        }
        
        public static string PROCESSING_EXCEPTION {
            get {
                return ResourceManager.GetString("PROCESSING_EXCEPTION", resourceCulture);
            }
        }
        
        public static string MISSING_INVOICE_TEMPLATE {
            get {
                return ResourceManager.GetString("MISSING_INVOICE_TEMPLATE", resourceCulture);
            }
        }
        
        public static string DATE_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("DATE_TYPE_MISMATCH", resourceCulture);
            }
        }
        
        public static string UNSUPPORTED_PLATFORM {
            get {
                return ResourceManager.GetString("UNSUPPORTED_PLATFORM", resourceCulture);
            }
        }
        
        public static string MISSING_TAGS {
            get {
                return ResourceManager.GetString("MISSING_TAGS", resourceCulture);
            }
        }
        
        public static string VAT_NUM_INCORRECT_LENGTH {
            get {
                return ResourceManager.GetString("VAT_NUM_INCORRECT_LENGTH", resourceCulture);
            }
        }
        
        public static string VAT_NUM_ALL_DIGITS_ARE_SAME {
            get {
                return ResourceManager.GetString("VAT_NUM_ALL_DIGITS_ARE_SAME", resourceCulture);
            }
        }
        
        public static string VAT_NUM_INCORRECT_SIGN {
            get {
                return ResourceManager.GetString("VAT_NUM_INCORRECT_SIGN", resourceCulture);
            }
        }
        
        public static string VAT_NUM_INCORRECT_FORMAT {
            get {
                return ResourceManager.GetString("VAT_NUM_INCORRECT_FORMAT", resourceCulture);
            }
        }
        
        public static string VAT_NUM_ZERO_AT_FIRST_OR_THIRD_POSSITION {
            get {
                return ResourceManager.GetString("VAT_NUM_ZERO_AT_FIRST_OR_THIRD_POSSITION", resourceCulture);
            }
        }
        
        public static string VAT_NUM_INCORRECT_CHECK_SUM {
            get {
                return ResourceManager.GetString("VAT_NUM_INCORRECT_CHECK_SUM", resourceCulture);
            }
        }
        
        public static string VAT_NUM_LENGTH_NINE {
            get {
                return ResourceManager.GetString("VAT_NUM_LENGTH_NINE", resourceCulture);
            }
        }
        
        public static string INVALID_RESET_ID {
            get {
                return ResourceManager.GetString("INVALID_RESET_ID", resourceCulture);
            }
        }
        
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        public static string INVALID_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        public static string INVALID_ACTIVATION_ID {
            get {
                return ResourceManager.GetString("INVALID_ACTIVATION_ID", resourceCulture);
            }
        }
        
        public static string INVALID_USER_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_USER_TOKEN", resourceCulture);
            }
        }
        
        public static string INVALID_TOKEN_CLAIMS {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_CLAIMS", resourceCulture);
            }
        }
        
        public static string INVALID_PROCESSING_BATCH_KEY {
            get {
                return ResourceManager.GetString("INVALID_PROCESSING_BATCH_KEY", resourceCulture);
            }
        }
        
        public static string INVALID_TEMPLATE_ID {
            get {
                return ResourceManager.GetString("INVALID_TEMPLATE_ID", resourceCulture);
            }
        }
        
        public static string INVALID_TEMPLATE_NAME {
            get {
                return ResourceManager.GetString("INVALID_TEMPLATE_NAME", resourceCulture);
            }
        }
        
        public static string INVALID_CONTENT_TYPE {
            get {
                return ResourceManager.GetString("INVALID_CONTENT_TYPE", resourceCulture);
            }
        }
        
        public static string INVALID_INVOICE_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_INVOICE_NUMBER", resourceCulture);
            }
        }
        
        public static string INVALID_PRIVATE_KEY {
            get {
                return ResourceManager.GetString("INVALID_PRIVATE_KEY", resourceCulture);
            }
        }
        
        public static string INVALID_ASSOCIATED_USER {
            get {
                return ResourceManager.GetString("INVALID_ASSOCIATED_USER", resourceCulture);
            }
        }
        
        public static string INVALID_API_VERSION {
            get {
                return ResourceManager.GetString("INVALID_API_VERSION", resourceCulture);
            }
        }
        
        public static string BUSINESS_LOCK_ENABLED {
            get {
                return ResourceManager.GetString("BUSINESS_LOCK_ENABLED", resourceCulture);
            }
        }
    }
}
