//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokanPages.Backend.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationCodes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationCodes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TokanPages.Backend.Shared.Resources.ValidationCodes", typeof(ValidationCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        public static string EMAIL_TOO_LONG {
            get {
                return ResourceManager.GetString("EMAIL_TOO_LONG", resourceCulture);
            }
        }
        
        public static string FIRST_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("FIRST_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        public static string LAST_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("LAST_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        public static string LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        public static string MESSAGE_TOO_LONG {
            get {
                return ResourceManager.GetString("MESSAGE_TOO_LONG", resourceCulture);
            }
        }
        
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        public static string SUBJECT_TOO_LONG {
            get {
                return ResourceManager.GetString("SUBJECT_TOO_LONG", resourceCulture);
            }
        }
        
        public static string TITLE_TOO_LONG {
            get {
                return ResourceManager.GetString("TITLE_TOO_LONG", resourceCulture);
            }
        }
        
        public static string USERALIAS_TOO_LONG {
            get {
                return ResourceManager.GetString("USERALIAS_TOO_LONG", resourceCulture);
            }
        }
        
        public static string PASSWORD_TOO_LONG {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_LONG", resourceCulture);
            }
        }
        
        public static string NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("NAME_TOO_LONG", resourceCulture);
            }
        }
        
        public static string LENGTH_TOO_LONG_100 {
            get {
                return ResourceManager.GetString("LENGTH_TOO_LONG_100", resourceCulture);
            }
        }
        
        public static string INVALID_FILE_SIZE {
            get {
                return ResourceManager.GetString("INVALID_FILE_SIZE", resourceCulture);
            }
        }
        
        public static string INVALID_VAT {
            get {
                return ResourceManager.GetString("INVALID_VAT", resourceCulture);
            }
        }
        
        public static string TOO_LONG_USER_IMAGE_NAME {
            get {
                return ResourceManager.GetString("TOO_LONG_USER_IMAGE_NAME", resourceCulture);
            }
        }
        
        public static string TOO_LONG_USER_VIDEO_NAME {
            get {
                return ResourceManager.GetString("TOO_LONG_USER_VIDEO_NAME", resourceCulture);
            }
        }
        
        public static string INVALID_GUID_VALUE {
            get {
                return ResourceManager.GetString("INVALID_GUID_VALUE", resourceCulture);
            }
        }
        
        public static string TOO_LONG_MEDIA_NAME {
            get {
                return ResourceManager.GetString("TOO_LONG_MEDIA_NAME", resourceCulture);
            }
        }
        
        public static string TOO_LONG_MEDIA_TYPE {
            get {
                return ResourceManager.GetString("TOO_LONG_MEDIA_TYPE", resourceCulture);
            }
        }
        
        public static string NOT_SPECIFIED_MEDIA_TARGET {
            get {
                return ResourceManager.GetString("NOT_SPECIFIED_MEDIA_TARGET", resourceCulture);
            }
        }
        
        public static string PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        public static string PASSWORD_MISSING_CHAR {
            get {
                return ResourceManager.GetString("PASSWORD_MISSING_CHAR", resourceCulture);
            }
        }
        
        public static string PASSWORD_MISSING_NUMBER {
            get {
                return ResourceManager.GetString("PASSWORD_MISSING_NUMBER", resourceCulture);
            }
        }
        
        public static string PASSWORD_MISSING_SMALL_LETTER {
            get {
                return ResourceManager.GetString("PASSWORD_MISSING_SMALL_LETTER", resourceCulture);
            }
        }
        
        public static string PASSWORD_MISSING_LARGE_LETTER {
            get {
                return ResourceManager.GetString("PASSWORD_MISSING_LARGE_LETTER", resourceCulture);
            }
        }
        
        public static string LENGTH_TOO_LONG_225 {
            get {
                return ResourceManager.GetString("LENGTH_TOO_LONG_225", resourceCulture);
            }
        }
        
        public static string LENGTH_TOO_LONG_500 {
            get {
                return ResourceManager.GetString("LENGTH_TOO_LONG_500", resourceCulture);
            }
        }
        
        public static string TOO_MANY_TAGS {
            get {
                return ResourceManager.GetString("TOO_MANY_TAGS", resourceCulture);
            }
        }
        
        public static string ISO_VALUE_TOO_LONG {
            get {
                return ResourceManager.GetString("ISO_VALUE_TOO_LONG", resourceCulture);
            }
        }
    }
}
