version: "3.8"

services:
  articles-api:
    build:
      context: TokanPages.WebApi/TokanPages.Articles
      args:
        - ENV_VALUE=Testing
      dockerfile: articles.dockerfile
    hostname: articles
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  content-api:
    build:
      context: TokanPages.WebApi/TokanPages.Content
      args:
        - ENV_VALUE=Testing
      dockerfile: content.dockerfile
    hostname: content
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  sender-api:
    build:
      context: TokanPages.WebApi/TokanPages.Sender
      args:
        - ENV_VALUE=Testing
      dockerfile: sender.dockerfile
    hostname: sender
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  revenue-api:
    build:
      context: TokanPages.WebApi/TokanPages.Revenue
      args:
        - ENV_VALUE=Testing
      dockerfile: revenue.dockerfile
    hostname: revenue
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  users-api:
    build:
      context: TokanPages.WebApi/TokanPages.Users
      args:
        - ENV_VALUE=Testing
      dockerfile: users.dockerfile
    hostname: users
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  invoicing-api:
    build:
      context: TokanPages.WebApi/TokanPages.Invoicing
      args:
        - ENV_VALUE=Testing
      dockerfile: invoicing.dockerfile
    hostname: invoicing
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  logger-api:
    build:
      context: TokanPages.WebApi/TokanPages.Logger
      args:
        - ENV_VALUE=Testing
      dockerfile: logger.dockerfile
    hostname: logger
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  notifications-api:
    build:
      context: TokanPages.WebApi/TokanPages.Notifications
      args:
        - ENV_VALUE=Testing
      dockerfile: notifications.dockerfile
    hostname: notifications
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  chat-api:
    build:
      context: TokanPages.WebApi/TokanPages.Chat
      args:
        - ENV_VALUE=Testing
      dockerfile: chat.dockerfile
    hostname: chat
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  gateway-api:
    build:
      context: TokanPages.WebApi/TokanPages.Gateway
      args:
        - ENV_VALUE=Testing
      dockerfile: gateway.dockerfile
    hostname: gateway
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/adf9015c-8c97-47bb-aabd-27827bc78822/secrets-docker.json:/app/appsettings.Testing.json:ro

  hosted-services-api:
    build:
      context: TokanPages.WebApi/TokanPages.HostedServices
      args:
        - ENV_VALUE=Testing
      dockerfile: hosted.dockerfile
    hostname: hosted-services
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /Users/tomkandula/.microsoft/usersecrets/8b3e70b5-d8ea-4e82-a5b9-080a2e2d1f40/secrets.json:/app/appsettings.Testing.json:ro

  frontend-app:
    build:
      context: TokanPages.ClientApp
      args:
        - ENV_VALUE=Testing
        - API_VERSION=${API_VERSION}
        - APP_VERSION=${APP_VERSION}
        - APP_BUILD_TEST=${APP_BUILD_TEST}
        - APP_DATE_TIME=${APP_DATE_TIME}
        - APP_BACKEND=http://${APP_BACKEND}
        - SONAR_TOKEN=${SONAR_TOKEN}
        - SONAR_KEY=${SONAR_KEY}
        - SONAR_HOST=${SONAR_HOST}
      dockerfile: clientapp.dockerfile
    hostname: frontend
    restart: on-failure
    networks:
      - xnet
    ports:
      - "3000:80"
    volumes:
      - ./TokanPages.ClientApp/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-base.conf:/etc/nginx/nginx-base.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-proxy.conf:/etc/nginx/nginx-proxy.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-ui-paths.conf:/etc/nginx/nginx-ui-paths.conf:ro

networks:
  xnet:
    driver: bridge