version: "3.8"

services:
  articles-api:
    build:
      context: TokanPages.WebApi/TokanPages.Articles
      args:
        - ENV_VALUE=Production
      dockerfile: articles.dockerfile
    hostname: articles
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  content-api:
    build:
      context: TokanPages.WebApi/TokanPages.Content
      args:
        - ENV_VALUE=Production
      dockerfile: content.dockerfile
    hostname: content
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  sender-api:
    build:
      context: TokanPages.WebApi/TokanPages.Sender
      args:
        - ENV_VALUE=Production
      dockerfile: sender.dockerfile
    hostname: sender
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  revenue-api:
    build:
      context: TokanPages.WebApi/TokanPages.Revenue
      args:
        - ENV_VALUE=Production
      dockerfile: revenue.dockerfile
    hostname: revenue
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  users-api:
    build:
      context: TokanPages.WebApi/TokanPages.Users
      args:
        - ENV_VALUE=Production
      dockerfile: users.dockerfile
    hostname: users
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  invoicing-api:
    build:
      context: TokanPages.WebApi/TokanPages.Invoicing
      args:
        - ENV_VALUE=Production
      dockerfile: invoicing.dockerfile
    hostname: invoicing
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  logger-api:
    build:
      context: TokanPages.WebApi/TokanPages.Logger
      args:
        - ENV_VALUE=Production
      dockerfile: logger.dockerfile
    hostname: logger
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  notifications-api:
    build:
      context: TokanPages.WebApi/TokanPages.Notifications
      args:
        - ENV_VALUE=Production
      dockerfile: notifications.dockerfile
    hostname: notifications
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  chat-api:
    build:
      context: TokanPages.WebApi/TokanPages.Chat
      args:
        - ENV_VALUE=Production
      dockerfile: chat.dockerfile
    hostname: chat
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  gateway-api:
    build:
      context: TokanPages.WebApi/TokanPages.Gateway
      args:
        - ENV_VALUE=Production
      dockerfile: gateway.dockerfile
    hostname: gateway
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-gw-prod.json:/app/appsettings.Production.json:ro

  hosted-services-api:
    build:
      context: TokanPages.WebApi/TokanPages.HostedServices
      args:
        - ENV_VALUE=Production
      dockerfile: hosted.dockerfile
    hostname: hosted-services
    restart: on-failure
    networks:
      - xnet
    expose:
      - "80"
    volumes:
      - /opt/configs/tokanpages-apis-prod.json:/app/appsettings.Production.json:ro

  frontend-app:
    build:
      context: TokanPages.ClientApp
      args:
        - ENV_VALUE=Production
        - API_VERSION=${API_VERSION}
        - APP_VERSION=${APP_VERSION}
        - APP_BUILD_TEST=${APP_BUILD_TEST}
        - APP_DATE_TIME=${APP_DATE_TIME}
        - APP_BACKEND=https://${APP_BACKEND}
        - SONAR_TOKEN=${SONAR_TOKEN}
        - SONAR_KEY=${SONAR_KEY}
        - SONAR_HOST=${SONAR_HOST}
      dockerfile: clientapp.dockerfile
    hostname: frontend
    restart: on-failure
    networks:
      - xnet
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./TokanPages.ClientApp/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-base.conf:/etc/nginx/nginx-base.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-proxy.conf:/etc/nginx/nginx-proxy.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-ssl.conf:/etc/nginx/nginx-ssl.conf:ro
      - ./TokanPages.ClientApp/nginx/nginx-ui-paths.conf:/etc/nginx/nginx-ui-paths.conf:ro
      - /opt/certs/wildcard-tomkandula.com.chain:/etc/nginx/wildcard-tomkandula.com.chain:ro
      - /opt/certs/wildcard-tomkandula.com.key:/etc/nginx/wildcard-tomkandula.com.key:ro
      - /opt/certs/wildcard-tomkandula.com.ca:/etc/nginx/wildcard-tomkandula.com.ca:ro
      - /opt/certs/ffdhe2048.txt:/etc/nginx/ffdhe2048.txt:ro

networks:
  xnet:
    driver: bridge