SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [operation].[VatNumberPatterns](
	[Id] [uniqueidentifier] NOT NULL,
	[CountryCode] [nvarchar](2) NOT NULL,
	[Pattern] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_VatNumberPatterns] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
