import { OperationStatus } from "../../../Shared/enums";
import { ContentPageDataState } from "../../../Store/States";

export const ContentPageData: ContentPageDataState = {
    status: OperationStatus.notStarted,
    isLoading: false,
    pageId: undefined,
    languageId: undefined,
    components: {
        pagePdfViewer: {
            language: "",
            caption: "",
            text: "",
        },
        sectionShowcase: {
            language: "",
            caption: "",
            heading: "",
            text: "",
            image: "",
            action: {
                text: "",
                href: "",
            },
        },
        accountUserNotes: {
            language: "",
            caption: "",
            description: "",
            listLabel: "",
            noteLabel: "",
            buttons: {
                removeText: "",
                clearText: "",
                saveText: "",
            },
        },
        accountSettings: {
            language: "",
            sectionAccessDenied: {
                accessDeniedCaption: "",
                accessDeniedPrompt: [""],
                homeButtonText: "",
            },
            sectionAccountInformation: {
                caption: "",
                labelUserId: "",
                labelEmailStatus: {
                    label: "",
                    negative: "",
                    positive: "",
                },
                labelUserAlias: "",
                labelFirstName: "",
                labelLastName: "",
                labelEmail: "",
                labelDescription: "",
                labelUserAvatar: "",
                updateButtonText: "",
                uploadAvatarButtonText: "",
            },
            sectionAccountPassword: {
                caption: "",
                labelOldPassword: "",
                labelNewPassword: "",
                labelConfirmPassword: "",
                updateButtonText: "",
            },
            sectionAccountDeactivation: {
                caption: "",
                warningText: [""],
                deactivateButtonText: "",
            },
            sectionAccountRemoval: {
                caption: "",
                warningText: [""],
                deleteButtonText: "",
            },
        },
        accountActivate: {
            language: "",
            fallback: {
                caption: "",
                text: [""],
            },
            onVerifying: {
                text1: "",
                text2: "",
                type: "",
                caption: "",
                button: "",
            },
            onProcessing: {
                text1: "",
                text2: "",
                type: "",
                caption: "",
                button: "",
            },
            onSuccess: {
                noBusinessLock: {
                    text1: "",
                    text2: "",
                },
                businessLock: {
                    text1: "",
                    text2: "",
                },
                type: "",
                caption: "",
                button: "",
            },
            onError: {
                text1: "",
                text2: "",
                type: "",
                caption: "",
                button: "",
            },
        },
        pageArticle: {
            language: "",
            button: "",
            textReadCount: "",
            textFirstName: "",
            textSurname: "",
            textRegistered: "",
            textLanguage: "",
            textReadTime1: "",
            textReadTime2: "",
            textPublished: "",
            textUpdated: "",
            textWritten: "",
            textAbout: "",
        },
        pageArticles: {
            language: "",
            caption: "",
            labels: {
                placeholder: "",
                buttonSearch: "",
                buttonClear: "",
                textEmptySearch1: "",
                textEmptySearch2: "",
                textSelectAll: "",
            },
            content: [""],
        },
        sectionArticle: {
            language: "",
            caption: "",
            title: "",
            description: "",
            text: "",
            action: {
                text: "",
                href: "",
            },
            image1: "",
            image2: "",
            image3: "",
            image4: "",
        },
        pageBusinessForm: {
            language: "",
            caption: "",
            buttonText: "",
            companyLabel: "",
            firstNameLabel: "",
            lastNameLabel: "",
            emailLabel: "",
            phoneLabel: "",
            description: {
                label: "",
                rows: 0,
                required: false,
            },
            technology: {
                caption: "",
                canDisplay: false,
                items: [],
            },
            pricing: {
                caption: "",
                disclaimer: "",
                items: [],
            },
            presentation: {
                image: {
                    link: "",
                    title: "",
                    alt: "",
                    width: 0,
                    heigh: 0,
                },
                title: "",
                subtitle: "",
                icon: {
                    name: "",
                    href: "",
                },
                description: "",
                logos: {
                    title: "",
                    images: [],
                },
            },
        },
        sectionClients: {
            language: "",
            caption: "",
            images: [],
        },
        sectionContactForm: {
            language: "",
            caption: "",
            button: "",
            consent: "",
            labelFirstName: "",
            labelLastName: "",
            labelEmail: "",
            labelSubject: "",
            labelMessage: "",
            presentation: {
                image: {
                    link: "",
                    title: "",
                    alt: "",
                    width: 0,
                    heigh: 0,
                },
                title: "",
                subtitle: "",
                icon: {
                    name: "",
                    href: "",
                },
                description: "",
                logos: {
                    title: "",
                    images: [],
                },
            },
        },
        sectionCookiesPrompt: {
            language: "",
            caption: "",
            text: "",
            detail: "",
            loading: [],
            options: {
                enabled: false,
                necessaryLabel: "",
                statisticsLabel: "",
                marketingLabel: "",
                personalizationLabel: "",
            },
            buttons: {
                acceptButton: {
                    label: "",
                    enabled: false,
                },
                manageButton: {
                    label: "",
                    enabled: false,
                },
                closeButton: {
                    label: "",
                    enabled: false,
                },
            },
            days: 0,
        },
        sectionFeatured: {
            language: "",
            caption: "",
            text: "",
            title1: "",
            subtitle1: "",
            link1: "",
            image1: "",
            title2: "",
            subtitle2: "",
            link2: "",
            image2: "",
            title3: "",
            subtitle3: "",
            link3: "",
            image3: "",
        },
        layoutFooter: {
            language: "",
            terms: {
                text: "",
                href: "",
            },
            policy: {
                text: "",
                href: "",
            },
            copyright: "",
            reserved: "",
            icons: [],
        },
        layoutHeader: {
            language: "",
            photo: {
                w360: "",
                w720: "",
                w1440: "",
                w2880: "",
            },
            caption: "",
            subtitle: "",
            description: "",
            hint: "",
            primaryButton: {
                text: "",
                href: "",
            },
            secondaryButton: {
                text: "",
                href: "",
            },
            tertiaryButton: {
                text: "",
                href: "",
            },
        },
        layoutNavigation: {
            language: "",
            logo: "",
            languageMenu: {
                caption: "",
            },
            signup: {
                caption: "",
                link: "",
            },
            userInfo: {
                textUserAlias: "",
                textRegistered: "",
                textRoles: "",
                textPermissions: "",
                textButton: "",
            },
            menu: {
                image: "",
                items: [],
            },
        },
        sectionNewsletter: {
            language: "",
            caption: "",
            text: "",
            button: "",
            labelEmail: "",
        },
        pageNewsletterRemove: {
            language: "",
            contentPre: {
                caption: "",
                text1: "",
                text2: "",
                text3: "",
                button: "",
            },
            contentPost: {
                caption: "",
                text1: "",
                text2: "",
                text3: "",
                button: "",
            },
        },
        pageNewsletterUpdate: {
            language: "",
            caption: "",
            button: "",
            labelEmail: "",
        },
        pagePasswordReset: {
            language: "",
            caption: "",
            button: "",
            labelEmail: "",
        },
        sectionTechnologies: {
            language: "",
            caption: "",
            header: "",
            title1: "",
            text1: "",
            title2: "",
            text2: "",
            title3: "",
            text3: "",
            title4: "",
            text4: "",
        },
        templates: {
            language: "",
            forms: {
                textSigning: "",
                textSignup: "",
                textPasswordReset: "",
                textUpdatePassword: "",
                textBusinessForm: "",
                textContactForm: "",
                textCheckoutForm: "",
                textNewsletter: "",
                textAccountSettings: "",
            },
            templates: {
                application: {
                    unexpectedStatus: "",
                    unexpectedError: "",
                    validationError: "",
                    nullError: "",
                },
                password: {
                    emailInvalid: "",
                    nameInvalid: "",
                    surnameInvalid: "",
                    passwordInvalid: "",
                    missingTerms: "",
                    missingNumber: "",
                    missingLargeLetter: "",
                    missingSmallLetter: "",
                    resetSuccess: [""],
                    resetWarning: [""],
                    updateSuccess: [""],
                    updateWarning: [""],
                },
                articles: {
                    success: "",
                    warning: "",
                    error: "",
                    likesHintAnonym: "",
                    likesHintUser: "",
                    maxLikesReached: "",
                },
                newsletter: {
                    success: [""],
                    warning: [""],
                    generalError: [""],
                    removalError: [""],
                },
                messageOut: {
                    success: [""],
                    warning: [""],
                    error: [""],
                },
                user: {
                    deactivation: [""],
                    removal: [""],
                    updateSuccess: [""],
                    updateWarning: [""],
                    emailVerification: [""],
                    signingWarning: [""],
                    signupSuccess: [""],
                    signupWarning: [""],
                },
                payments: {
                    checkoutWarning: "",
                },
            },
        },
        sectionTestimonials: {
            language: "",
            caption: "",
            subtitle: "",
            photo1: "",
            name1: "",
            linkedIn1: "",
            occupation1: "",
            text1: "",
            photo2: "",
            name2: "",
            linkedIn2: "",
            occupation2: "",
            text2: "",
            photo3: "",
            name3: "",
            linkedIn3: "",
            occupation3: "",
            text3: "",
        },
        sectionSocials: {
            language: "",
            caption: "",
            social1: {
                images: {
                    header: "",
                    avatar: "",
                    icon: "",
                },
                textTitle: "",
                textSubtitle: "",
                textComment: "",
                action: {
                    text: "",
                    href: "",
                },
            },
            social2: {
                images: {
                    header: "",
                    avatar: "",
                    icon: "",
                },
                textTitle: "",
                textSubtitle: "",
                textComment: "",
                action: {
                    text: "",
                    href: "",
                },
            },
            social3: {
                images: {
                    header: "",
                    avatar: "",
                    icon: "",
                },
                textTitle: "",
                textSubtitle: "",
                textComment: "",
                action: {
                    text: "",
                    href: "",
                },
            },
        },
        pagePasswordUpdate: {
            language: "",
            caption: "",
            button: "",
            labelNewPassword: "",
            labelVerifyPassword: "",
        },
        pageResume: {
            language: "",
            caption: "",
            photo: {
                href: "",
                text: "",
            },
            translations: {
                singular: {
                    yearLabel: "",
                    monthLabel: "",
                },
                plural: {
                    yearsLabel: "",
                    monthsLabel: "",
                },
            },
            resume: {
                header: {
                    fullName: "",
                    mobilePhone: "",
                    email: "",
                    www: {
                        text: "",
                        href: "",
                    },
                    github: {
                        text: "",
                        href: "",
                    },
                },
                summary: {
                    caption: "",
                    text: "",
                },
                achievements: {
                    caption: "",
                    list: [],
                },
                experience: {
                    caption: "",
                    list: [],
                },
                education: {
                    caption: "",
                    list: [],
                },
                interests: {
                    caption: "",
                    list: [],
                },
            },
        },
        accountUserSignin: {
            language: "",
            caption: "",
            button: "",
            link1: {
                text: "",
                href: "",
            },
            link2: {
                text: "",
                href: "",
            },
            labelEmail: "",
            labelPassword: "",
            consent: "",
            securityNews: [],
        },
        accountUserSignout: {
            language: "",
            caption: "",
            onProcessing: [""],
            onFinish: [""],
            buttonText: "",
        },
        accountUserSignup: {
            language: "",
            caption: "",
            button: "",
            link: {
                text: "",
                href: "",
            },
            warning: {
                textPre: "",
                textList: [""],
                textPost: [""],
                textNist: {
                    text: "",
                    href: "",
                },
            },
            consent: "",
            labelFirstName: "",
            labelLastName: "",
            labelEmail: "",
            labelPassword: "",
        },
        legalPolicy: {
            language: "",
            items: [],
        },
        legalTerms: {
            language: "",
            items: [],
        },
        pageAbout: {
            language: "",
            items: [],
        },
        pageStory: {
            language: "",
            items: [],
        },
        pageShowcase: {
            language: "",
            items: [],
        },
        leisureBicycle: {
            language: "",
            items: [],
        },
        leisureElectronics: {
            language: "",
            items: [],
        },
        leisureFootball: {
            language: "",
            items: [],
        },
        leisureGuitar: {
            language: "",
            items: [],
        },
        leisurePhotography: {
            language: "",
            items: [],
        },
    },
};
