// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TokanPages.Persistence.Database.Migrations
{
    public partial class VideosAndMessagesTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ServiceBusMessages",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IsConsumed = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ServiceBusMessages", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UploadedVideos",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TicketId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SourceBlobUri = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TargetVideoUri = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TargetThumbnailUri = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    IsSourceDeleted = table.Column<bool>(type: "bit", nullable: false),
                    ProcessingWarning = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true),
                    InputSizeInBytes = table.Column<long>(type: "bigint", nullable: false),
                    OutputSizeInBytes = table.Column<long>(type: "bigint", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ModifiedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UploadedVideos", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ServiceBusMessages");

            migrationBuilder.DropTable(
                name: "UploadedVideos");
        }
    }
}
