// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TokanPages.Persistence.Database.Migrations
{
    public partial class UpdateNavigationProps : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_IssuedInvoices_Users_UserId",
                table: "IssuedInvoices");

            migrationBuilder.DropForeignKey(
                name: "FK_UserBankAccounts_Users_UserId",
                table: "UserBankAccounts");

            migrationBuilder.DropForeignKey(
                name: "FK_UserCompanies_Users_UserId",
                table: "UserCompanies");

            migrationBuilder.AddForeignKey(
                name: "FK_IssuedInvoices_Users",
                table: "IssuedInvoices",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_UserBankAccounts_Users",
                table: "UserBankAccounts",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_UserCompanies_Users",
                table: "UserCompanies",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_IssuedInvoices_Users",
                table: "IssuedInvoices");

            migrationBuilder.DropForeignKey(
                name: "FK_UserBankAccounts_Users",
                table: "UserBankAccounts");

            migrationBuilder.DropForeignKey(
                name: "FK_UserCompanies_Users",
                table: "UserCompanies");

            migrationBuilder.AddForeignKey(
                name: "FK_IssuedInvoices_Users_UserId",
                table: "IssuedInvoices",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_UserBankAccounts_Users_UserId",
                table: "UserBankAccounts",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_UserCompanies_Users_UserId",
                table: "UserCompanies",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
