// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TokanPages.Persistence.Database.Migrations
{
    public partial class ArticleCategoryWithLanguageId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "LanguageId",
                table: "ArticleCategory",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_ArticleCategory_LanguageId",
                table: "ArticleCategory",
                column: "LanguageId");

            migrationBuilder.AddForeignKey(
                name: "FK_ArticleCategory_Language",
                table: "ArticleCategory",
                column: "LanguageId",
                principalTable: "Languages",
                principalColumn: "Id");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ArticleCategory_Language",
                table: "ArticleCategory");

            migrationBuilder.DropIndex(
                name: "IX_ArticleCategory_LanguageId",
                table: "ArticleCategory");

            migrationBuilder.DropColumn(
                name: "LanguageId",
                table: "ArticleCategory");
        }
    }
}
