// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TokanPages.Persistence.Database.Migrations
{
    public partial class ChangeTableNames : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "UserInfo",
                newName: "UserInformation");

            migrationBuilder.RenameTable(
                name: "SubscriptionPricing",
                newName: "SubscriptionsPricing");

            migrationBuilder.RenameTable(
                name: "BusinessInquiry",
                newName: "BusinessInquiries");

            migrationBuilder.RenameTable(
                name: "ArticleCategory",
                newName: "ArticleCategories");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "UserInformation",
                newName: "UserInfo");

            migrationBuilder.RenameTable(
                name: "SubscriptionsPricing",
                newName: "SubscriptionPricing");

            migrationBuilder.RenameTable(
                name: "BusinessInquiries",
                newName: "BusinessInquiry");

            migrationBuilder.RenameTable(
                name: "ArticleCategories",
                newName: "ArticleCategory");
        }
    }
}
