// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TokanPages.Persistence.Database.Migrations
{
    public partial class ApplyOperationSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "operation");

            migrationBuilder.RenameTable(
                name: "WebNotifications",
                newName: "WebNotifications",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "VatNumberPatterns",
                newName: "VatNumberPatterns",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserTokens",
                newName: "UserTokens",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserSubscriptions",
                newName: "UserSubscriptions",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Users",
                newName: "Users",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserRoles",
                newName: "UserRoles",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserRefreshTokens",
                newName: "UserRefreshTokens",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserPhotos",
                newName: "UserPhotos",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserPermissions",
                newName: "UserPermissions",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserPaymentsHistory",
                newName: "UserPaymentsHistory",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserPayments",
                newName: "UserPayments",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserNotes",
                newName: "UserNotes",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserMessagesCache",
                newName: "UserMessagesCache",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserMessages",
                newName: "UserMessages",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserInformation",
                newName: "UserInformation",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserCompanies",
                newName: "UserCompanies",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UserBankAccounts",
                newName: "UserBankAccounts",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "UploadedVideos",
                newName: "UploadedVideos",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "SubscriptionsPricing",
                newName: "SubscriptionsPricing",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "ServiceBusMessages",
                newName: "ServiceBusMessages",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Roles",
                newName: "Roles",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "PushNotificationTags",
                newName: "PushNotificationTags",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "PushNotifications",
                newName: "PushNotifications",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "PushNotificationLogs",
                newName: "PushNotificationLogs",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "PhotoGears",
                newName: "PhotoGears",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "PhotoCategories",
                newName: "PhotoCategories",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Permissions",
                newName: "Permissions",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Newsletters",
                newName: "Newsletters",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Languages",
                newName: "Languages",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "IssuedInvoices",
                newName: "IssuedInvoices",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "InvoiceTemplates",
                newName: "InvoiceTemplates",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "HttpRequests",
                newName: "HttpRequests",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "DefaultPermissions",
                newName: "DefaultPermissions",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "CategoryNames",
                newName: "CategoryNames",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "BusinessInquiries",
                newName: "BusinessInquiries",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "BatchInvoicesProcessing",
                newName: "BatchInvoicesProcessing",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "BatchInvoices",
                newName: "BatchInvoices",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "BatchInvoiceItems",
                newName: "BatchInvoiceItems",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "ArticleTags",
                newName: "ArticleTags",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Articles",
                newName: "Articles",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "ArticleLikes",
                newName: "ArticleLikes",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "ArticleCounts",
                newName: "ArticleCounts",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "ArticleCategories",
                newName: "ArticleCategories",
                newSchema: "operation");

            migrationBuilder.RenameTable(
                name: "Albums",
                newName: "Albums",
                newSchema: "operation");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "WebNotifications",
                schema: "operation",
                newName: "WebNotifications");

            migrationBuilder.RenameTable(
                name: "VatNumberPatterns",
                schema: "operation",
                newName: "VatNumberPatterns");

            migrationBuilder.RenameTable(
                name: "UserTokens",
                schema: "operation",
                newName: "UserTokens");

            migrationBuilder.RenameTable(
                name: "UserSubscriptions",
                schema: "operation",
                newName: "UserSubscriptions");

            migrationBuilder.RenameTable(
                name: "Users",
                schema: "operation",
                newName: "Users");

            migrationBuilder.RenameTable(
                name: "UserRoles",
                schema: "operation",
                newName: "UserRoles");

            migrationBuilder.RenameTable(
                name: "UserRefreshTokens",
                schema: "operation",
                newName: "UserRefreshTokens");

            migrationBuilder.RenameTable(
                name: "UserPhotos",
                schema: "operation",
                newName: "UserPhotos");

            migrationBuilder.RenameTable(
                name: "UserPermissions",
                schema: "operation",
                newName: "UserPermissions");

            migrationBuilder.RenameTable(
                name: "UserPaymentsHistory",
                schema: "operation",
                newName: "UserPaymentsHistory");

            migrationBuilder.RenameTable(
                name: "UserPayments",
                schema: "operation",
                newName: "UserPayments");

            migrationBuilder.RenameTable(
                name: "UserNotes",
                schema: "operation",
                newName: "UserNotes");

            migrationBuilder.RenameTable(
                name: "UserMessagesCache",
                schema: "operation",
                newName: "UserMessagesCache");

            migrationBuilder.RenameTable(
                name: "UserMessages",
                schema: "operation",
                newName: "UserMessages");

            migrationBuilder.RenameTable(
                name: "UserInformation",
                schema: "operation",
                newName: "UserInformation");

            migrationBuilder.RenameTable(
                name: "UserCompanies",
                schema: "operation",
                newName: "UserCompanies");

            migrationBuilder.RenameTable(
                name: "UserBankAccounts",
                schema: "operation",
                newName: "UserBankAccounts");

            migrationBuilder.RenameTable(
                name: "UploadedVideos",
                schema: "operation",
                newName: "UploadedVideos");

            migrationBuilder.RenameTable(
                name: "SubscriptionsPricing",
                schema: "operation",
                newName: "SubscriptionsPricing");

            migrationBuilder.RenameTable(
                name: "ServiceBusMessages",
                schema: "operation",
                newName: "ServiceBusMessages");

            migrationBuilder.RenameTable(
                name: "Roles",
                schema: "operation",
                newName: "Roles");

            migrationBuilder.RenameTable(
                name: "PushNotificationTags",
                schema: "operation",
                newName: "PushNotificationTags");

            migrationBuilder.RenameTable(
                name: "PushNotifications",
                schema: "operation",
                newName: "PushNotifications");

            migrationBuilder.RenameTable(
                name: "PushNotificationLogs",
                schema: "operation",
                newName: "PushNotificationLogs");

            migrationBuilder.RenameTable(
                name: "PhotoGears",
                schema: "operation",
                newName: "PhotoGears");

            migrationBuilder.RenameTable(
                name: "PhotoCategories",
                schema: "operation",
                newName: "PhotoCategories");

            migrationBuilder.RenameTable(
                name: "Permissions",
                schema: "operation",
                newName: "Permissions");

            migrationBuilder.RenameTable(
                name: "Newsletters",
                schema: "operation",
                newName: "Newsletters");

            migrationBuilder.RenameTable(
                name: "Languages",
                schema: "operation",
                newName: "Languages");

            migrationBuilder.RenameTable(
                name: "IssuedInvoices",
                schema: "operation",
                newName: "IssuedInvoices");

            migrationBuilder.RenameTable(
                name: "InvoiceTemplates",
                schema: "operation",
                newName: "InvoiceTemplates");

            migrationBuilder.RenameTable(
                name: "HttpRequests",
                schema: "operation",
                newName: "HttpRequests");

            migrationBuilder.RenameTable(
                name: "DefaultPermissions",
                schema: "operation",
                newName: "DefaultPermissions");

            migrationBuilder.RenameTable(
                name: "CategoryNames",
                schema: "operation",
                newName: "CategoryNames");

            migrationBuilder.RenameTable(
                name: "BusinessInquiries",
                schema: "operation",
                newName: "BusinessInquiries");

            migrationBuilder.RenameTable(
                name: "BatchInvoicesProcessing",
                schema: "operation",
                newName: "BatchInvoicesProcessing");

            migrationBuilder.RenameTable(
                name: "BatchInvoices",
                schema: "operation",
                newName: "BatchInvoices");

            migrationBuilder.RenameTable(
                name: "BatchInvoiceItems",
                schema: "operation",
                newName: "BatchInvoiceItems");

            migrationBuilder.RenameTable(
                name: "ArticleTags",
                schema: "operation",
                newName: "ArticleTags");

            migrationBuilder.RenameTable(
                name: "Articles",
                schema: "operation",
                newName: "Articles");

            migrationBuilder.RenameTable(
                name: "ArticleLikes",
                schema: "operation",
                newName: "ArticleLikes");

            migrationBuilder.RenameTable(
                name: "ArticleCounts",
                schema: "operation",
                newName: "ArticleCounts");

            migrationBuilder.RenameTable(
                name: "ArticleCategories",
                schema: "operation",
                newName: "ArticleCategories");

            migrationBuilder.RenameTable(
                name: "Albums",
                schema: "operation",
                newName: "Albums");
        }
    }
}
