import { IApplicationState } from "./applicationState";
import { 
    ActivateAccountDefault,
    AddSubscriberDefault,
    GetAccountContentDefault,
    GetActivateAccountContentDefault,
    GetArticleFeatContentDefault,
    GetClientsContentDefault,
    GetContactFormContentDefault,
    GetCookiesPromptContentDefault,
    GetFeaturedContentDefault,
    GetFeaturesContentDefault,
    GetFooterContentDefault,
    GetHeaderContentDefault,
    GetNavigationContentDefault,
    GetNewsletterContentDefault,
    GetResetPasswordContentDefault,
    GetTestimonialsContentDefault,
    GetUnsubscribeContentDefault,
    GetUpdatePasswordContentDefault,
    GetUpdateSubscriberContentDefault,
    GetUserSigninContentDefault,
    GetUserSignoutContentDefault,
    GetUserSignupContentDefault,
    GetWrongPagePromptContentDefault,
    ListArticlesDefault,
    RaiseDialogDefault,
    RaiseErrorDefault,
    ReAuthenticateUserDefault,
    RemoveAccountDefault,
    RemoveSubscriberDefault,
    ResetUserPasswordDefault,
    SelectArticleDefault,
    SendMessageDefault,
    SigninUserDefault,
    SignupUserDefault,
    StoreUserDataDefault,
    UpdateArticleDefault,
    UpdateSubscriberDefault,
    UpdateUserDefault,
    UpdateUserPasswordDefault,
    UserLanguageDefault,
    GetPolicyContentDefault,
    GetTermsContentDefault,
    GetStoryContentDefault
} from "../Defaults";

export const ApplicationDefaults: IApplicationState = 
{
    applicationDialog: RaiseDialogDefault,
    applicationError: RaiseErrorDefault,
    applicationLanguage: UserLanguageDefault,
    applicationMessage: SendMessageDefault,
    articleListing: ListArticlesDefault,
    articleSelection: SelectArticleDefault,
    articleUpdated: UpdateArticleDefault,
    contentAccount: GetAccountContentDefault,
    contentActivateAccount: GetActivateAccountContentDefault,
    contentArticleFeatures: GetArticleFeatContentDefault,
    contentClients: GetClientsContentDefault,
    contentContactForm: GetContactFormContentDefault,
    contentCookiesPrompt: GetCookiesPromptContentDefault,
    contentFeatured: GetFeaturedContentDefault,
    contentFeatures: GetFeaturesContentDefault,
    contentFooter: GetFooterContentDefault,
    contentHeader: GetHeaderContentDefault,
    contentNavigation: GetNavigationContentDefault,
    contentNewsletter: GetNewsletterContentDefault,
    contentPolicy: GetPolicyContentDefault,
    contentResetPassword: GetResetPasswordContentDefault,
    contentStory: GetStoryContentDefault,
    contentTerms: GetTermsContentDefault,
    contentTestimonials: GetTestimonialsContentDefault,
    contentUnsubscribe: GetUnsubscribeContentDefault,
    contentUpdatePassword: GetUpdatePasswordContentDefault,
    contentUpdateSubscriber: GetUpdateSubscriberContentDefault,
    contentUserSignin: GetUserSigninContentDefault,
    contentUserSignout: GetUserSignoutContentDefault,
    contentUserSignup: GetUserSignupContentDefault,
    contentWrongPagePrompt: GetWrongPagePromptContentDefault,
    subscriberAdd: AddSubscriberDefault,
    subscriberRemove: RemoveSubscriberDefault,
    subscriberUpdate: UpdateSubscriberDefault,
    userActivate: ActivateAccountDefault,
    userDataStore: StoreUserDataDefault,
    userPasswordReset: ResetUserPasswordDefault,
    userPasswordUpdate: UpdateUserPasswordDefault,
    userReAuthenticate: ReAuthenticateUserDefault,
    userRemove: RemoveAccountDefault,
    userSignin: SigninUserDefault,
    userSignup: SignupUserDefault,
    userUpdate: UpdateUserDefault
};
