import { 
    ActivateAccountReducer,
    AddSubscriberReducer,
    GetAccountContentReducer,
    GetActivateAccountContentReducer,
    GetArticleFeaturesContentReducer,
    GetClientsContentReducer,
    GetContactFormContentReducer,
    GetCookiesPromptContentReducer,
    GetFeaturedContentReducer,
    GetFeaturesContentReducer,
    GetFooterContentReducer,
    GetHeaderContentReducer,
    GetNavigationContentReducer,
    GetNewsletterContentReducer,
    GetResetPasswordContentReducer,
    GetTestimonialsContentReducer,
    GetUnsubscribeContentReducer,
    GetUpdatePasswordContentReducer,
    GetUpdateSubscriberContentReducer,
    GetUserSigninContentReducer,
    GetUserSignoutContentReducer,
    GetUserSignupContentReducer,
    GetWrongPagePromptContentReducer,
    ListArticlesReducer,
    RaiseDialogReducer,
    RaiseErrorReducer,
    ReAuthenticateUserReducer,
    RemoveAccountReducer,
    RemoveSubscriberReducer,
    ResetUserPasswordReducer,
    SelectArticleReducer,
    SendMessageReducer,
    SigninUserReducer,
    SignupUserReducer,
    StoreUserDataReducer,
    UpdateArticleReducer,
    UpdateSubscriberReducer,
    UpdateUserPasswordReducer,
    UpdateUserReducer,
    UserLanguageReducer,
    GetPolicyContentReducer,
    GetTermsContentReducer,
    GetStoryContentReducer
} from "../Reducers";

export const ApplicationReducers = 
{
    raiseError: RaiseErrorReducer,
    raiseDialog: RaiseDialogReducer,
    userLanguage: UserLanguageReducer,
    listArticles: ListArticlesReducer,
    selectArticle: SelectArticleReducer,
    storeUserData: StoreUserDataReducer,
    sendMessage: SendMessageReducer,
    updateArticle: UpdateArticleReducer,
    addSubscriber: AddSubscriberReducer,
    updateSubscriber: UpdateSubscriberReducer,
    removeSubscriber: RemoveSubscriberReducer,
    removeAccount: RemoveAccountReducer,
    activateAccount: ActivateAccountReducer,
    reAuthenticateUser: ReAuthenticateUserReducer,
    signinUser: SigninUserReducer,
    signupUser: SignupUserReducer,
    updateUser: UpdateUserReducer,
    updateUserPassword: UpdateUserPasswordReducer,
    resetUserPassword: ResetUserPasswordReducer,
    getPolicyContent: GetPolicyContentReducer,
    getTermsContent: GetTermsContentReducer,
    getStoryContent: GetStoryContentReducer,
    getNavigationContent: GetNavigationContentReducer,
    getHeaderContent: GetHeaderContentReducer,
    getFooterContent: GetFooterContentReducer,
    getAccountContent: GetAccountContentReducer, 
    getActivateAccountContent: GetActivateAccountContentReducer,
    getClientsContent: GetClientsContentReducer,
    getFeaturesContent: GetFeaturesContentReducer,
    getArticleFeaturesContent: GetArticleFeaturesContentReducer,
    getFeaturedContent: GetFeaturedContentReducer,
    getTestimonialsContent: GetTestimonialsContentReducer,
    getNewsletterContent: GetNewsletterContentReducer,
    getContactFormContent: GetContactFormContentReducer,
    getCookiesPromptContent: GetCookiesPromptContentReducer,
    getWrongPagePromptContent: GetWrongPagePromptContentReducer,
    getUserSigninContent: GetUserSigninContentReducer,
    getUserSignupContent: GetUserSignupContentReducer,
    getUserSignoutContent: GetUserSignoutContentReducer,
    getUpdatePasswordContent: GetUpdatePasswordContentReducer,
    getResetPasswordContent: GetResetPasswordContentReducer,
    getUnsubscribeContent: GetUnsubscribeContentReducer,
    getUpdateSubscriberContent: GetUpdateSubscriberContentReducer
};
