import { 
    IActivateAccount,
    IAddSubscriber,
    IArticle,
    IArticles,
    IGetAccountContent,
    IGetActivateAccountContent,
    IGetArticleFeaturesContent,
    IGetClientsContent,
    IGetContactFormContent,
    IGetCookiesPromptContent,
    IGetFeaturedContent,
    IGetFeaturesContent,
    IGetFooterContent,
    IGetHeaderContent,
    IGetNavigationContent,
    IGetNewsletterContent,
    IGetResetPasswordContent,
    IGetTestimonialsContent,
    IGetUnsubscribeContent,
    IGetUpdatePasswordContent,
    IGetUpdateSubscriberContent,
    IGetUserSigninContent,
    IGetUserSignoutContent,
    IGetUserSignupContent,
    IGetWrongPagePromptContent,
    IRaiseDialog,
    IRaiseError,
    IReAuthenticateUser,
    IRemoveAccount,
    IRemoveSubscriber,
    IResetUserPassword,
    ISendMessage,
    ISigninUser,
    ISignupUser,
    IStoreUserData,
    IUpdateArticle,
    IUpdateSubscriber,
    IUpdateUser,
    IUpdateUserPassword,
    IUserLanguage,
    IGetPolicyContent,
    IGetTermsContent,
    IGetStoryContent
} from "../States";

export interface IApplicationState 
{
    raiseError: IRaiseError;
    raiseDialog: IRaiseDialog;
    userLanguage: IUserLanguage,
    listArticles: IArticles;
    selectArticle: IArticle;
    storeUserData: IStoreUserData,
    sendMessage: ISendMessage,
    updateArticle: IUpdateArticle,
    addSubscriber: IAddSubscriber,
    updateSubscriber: IUpdateSubscriber,
    removeSubscriber: IRemoveSubscriber,
    removeAccount: IRemoveAccount,
    activateAccount: IActivateAccount,
    reAuthenticateUser: IReAuthenticateUser,
    signinUser: ISigninUser,
    signupUser: ISignupUser,
    updateUser: IUpdateUser,
    updateUserPassword: IUpdateUserPassword,
    resetUserPassword: IResetUserPassword,
    getPolicyContent: IGetPolicyContent,
    getTermsContent: IGetTermsContent,
    getStoryContent: IGetStoryContent,
    getNavigationContent: IGetNavigationContent,
    getHeaderContent: IGetHeaderContent,
    getFooterContent: IGetFooterContent,
    getAccountContent: IGetAccountContent,
    getActivateAccountContent: IGetActivateAccountContent,
    getClientsContent: IGetClientsContent,
    getFeaturesContent: IGetFeaturesContent,
    getArticleFeaturesContent: IGetArticleFeaturesContent,
    getFeaturedContent: IGetFeaturedContent,
    getTestimonialsContent: IGetTestimonialsContent,
    getNewsletterContent: IGetNewsletterContent,
    getContactFormContent: IGetContactFormContent,
    getCookiesPromptContent: IGetCookiesPromptContent,
    getWrongPagePromptContent: IGetWrongPagePromptContent,
    getUserSigninContent: IGetUserSigninContent,
    getUserSignupContent: IGetUserSignupContent,
    getUserSignoutContent: IGetUserSignoutContent,
    getUpdatePasswordContent: IGetUpdatePasswordContent,
    getResetPasswordContent: IGetResetPasswordContent,
    getUnsubscribeContent: IGetUnsubscribeContent,
    getUpdateSubscriberContent: IGetUpdateSubscriberContent
}

export interface AppThunkAction<TAction> 
{
    (dispatch: (action: TAction) => void, getState: () => IApplicationState): void;
}
