import { 
    ActivateAccountReducer,
    AddSubscriberReducer,
    GetAccountContentReducer,
    GetActivateAccountContentReducer,
    GetArticleFeaturesContentReducer,
    GetClientsContentReducer,
    GetContactFormContentReducer,
    GetCookiesPromptContentReducer,
    GetFeaturedContentReducer,
    GetFeaturesContentReducer,
    GetFooterContentReducer,
    GetHeaderContentReducer,
    GetNavigationContentReducer,
    GetNewsletterContentReducer,
    GetResetPasswordContentReducer,
    GetTestimonialsContentReducer,
    GetUnsubscribeContentReducer,
    GetUpdatePasswordContentReducer,
    GetUpdateSubscriberContentReducer,
    GetUserSigninContentReducer,
    GetUserSignoutContentReducer,
    GetUserSignupContentReducer,
    GetWrongPagePromptContentReducer,
    ListArticlesReducer,
    ApplicationDialog,
    ApplicationError,
    ReAuthenticateUserReducer,
    RemoveAccountReducer,
    RemoveSubscriberReducer,
    ResetUserPasswordReducer,
    SelectArticleReducer,
    ApplicationMessage,
    SigninUserReducer,
    SignupUserReducer,
    StoreUserDataReducer,
    UpdateArticleReducer,
    UpdateSubscriberReducer,
    UpdateUserPasswordReducer,
    UpdateUserReducer,
    ApplicationLanguage,
    GetPolicyContentReducer,
    GetTermsContentReducer,
    GetStoryContentReducer
} from "../Reducers";

export const ApplicationReducers = 
{
    applicationDialog: ApplicationDialog,
    applicationError: ApplicationError,
    applicationLanguage: ApplicationLanguage,
    applicationMessage: ApplicationMessage,
    articleListing: ListArticlesReducer,
    articleSelection: SelectArticleReducer,
    articleUpdate: UpdateArticleReducer,
    contentAccount: GetAccountContentReducer,
    contentActivateAccount: GetActivateAccountContentReducer,
    contentArticleFeatures: GetArticleFeaturesContentReducer,
    contentClients: GetClientsContentReducer,
    contentContactForm: GetContactFormContentReducer,
    contentCookiesPrompt: GetCookiesPromptContentReducer,
    contentFeatured: GetFeaturedContentReducer,
    contentFeatures: GetFeaturesContentReducer,
    contentFooter: GetFooterContentReducer,
    contentHeader: GetHeaderContentReducer,
    contentNavigation: GetNavigationContentReducer,
    contentNewsletter: GetNewsletterContentReducer,
    contentPolicy: GetPolicyContentReducer,
    contentResetPassword: GetResetPasswordContentReducer,
    contentStory: GetStoryContentReducer,
    contentTerms: GetTermsContentReducer,
    contentTestimonials: GetTestimonialsContentReducer,
    contentUnsubscribe: GetUnsubscribeContentReducer,
    contentUpdatePassword: GetUpdatePasswordContentReducer,
    contentUpdateSubscriber: GetUpdateSubscriberContentReducer,
    contentUserSignin: GetUserSigninContentReducer,
    contentUserSignout: GetUserSignoutContentReducer,
    contentUserSignup: GetUserSignupContentReducer,
    contentWrongPagePrompt: GetWrongPagePromptContentReducer,
    subscriberAdd: AddSubscriberReducer,
    subscriberRemove: RemoveSubscriberReducer,
    subscriberUpdate: UpdateSubscriberReducer,
    userActivate: ActivateAccountReducer,
    userDataStore: StoreUserDataReducer,
    userPasswordReset: ResetUserPasswordReducer,
    userPasswordUpdate: UpdateUserPasswordReducer,
    userReAuthenticate: ReAuthenticateUserReducer,
    userRemove: RemoveAccountReducer,
    userSignin: SigninUserReducer,
    userSignup: SignupUserReducer,
    userUpdate: UpdateUserReducer
};
