import { IApplicationState } from "./applicationState";
import { 
    ActivateAccountDefault,
    AddSubscriberDefault,
    GetAccountContentDefault,
    GetActivateAccountContentDefault,
    GetArticleFeatContentDefault,
    GetClientsContentDefault,
    GetContactFormContentDefault,
    GetCookiesPromptContentDefault,
    GetFeaturedContentDefault,
    GetFeaturesContentDefault,
    GetFooterContentDefault,
    GetHeaderContentDefault,
    GetNavigationContentDefault,
    GetNewsletterContentDefault,
    GetResetPasswordContentDefault,
    GetTestimonialsContentDefault,
    GetUnsubscribeContentDefault,
    GetUpdatePasswordContentDefault,
    GetUpdateSubscriberContentDefault,
    GetUserSigninContentDefault,
    GetUserSignoutContentDefault,
    GetUserSignupContentDefault,
    GetWrongPagePromptContentDefault,
    ListArticlesDefault,
    RaiseDialogDefault,
    RaiseErrorDefault,
    ReAuthenticateUserDefault,
    RemoveAccountDefault,
    RemoveSubscriberDefault,
    ResetUserPasswordDefault,
    SelectArticleDefault,
    SendMessageDefault,
    SigninUserDefault,
    SignupUserDefault,
    StoreUserDataDefault,
    UpdateArticleDefault,
    UpdateSubscriberDefault,
    UpdateUserDefault,
    UpdateUserPasswordDefault,
    UserLanguageDefault,
    GetPolicyContentDefault,
    GetTermsContentDefault,
    GetStoryContentDefault
} from "../Defaults";

export const ApplicationDefaults: IApplicationState = 
{
    raiseError: RaiseErrorDefault,
    raiseDialog: RaiseDialogDefault,
    userLanguage: UserLanguageDefault,
    listArticles: ListArticlesDefault,
    selectArticle: SelectArticleDefault,
    storeUserData: StoreUserDataDefault,
    sendMessage: SendMessageDefault,
    updateArticle: UpdateArticleDefault,
    addSubscriber: AddSubscriberDefault,
    updateSubscriber: UpdateSubscriberDefault,
    removeSubscriber: RemoveSubscriberDefault,
    removeAccount: RemoveAccountDefault,
    activateAccount: ActivateAccountDefault,
    reAuthenticateUser: ReAuthenticateUserDefault,
    signinUser: SigninUserDefault,
    signupUser: SignupUserDefault,
    updateUser: UpdateUserDefault,
    updateUserPassword: UpdateUserPasswordDefault,
    resetUserPassword: ResetUserPasswordDefault,
    getPolicyContent: GetPolicyContentDefault,
    getTermsContent: GetTermsContentDefault,
    getStoryContent: GetStoryContentDefault,
    getNavigationContent: GetNavigationContentDefault,
    getHeaderContent: GetHeaderContentDefault,
    getFooterContent: GetFooterContentDefault,
    getAccountContent: GetAccountContentDefault,
    getActivateAccountContent: GetActivateAccountContentDefault,
    getClientsContent: GetClientsContentDefault,
    getFeaturesContent: GetFeaturesContentDefault,
    getArticleFeaturesContent: GetArticleFeatContentDefault,
    getFeaturedContent: GetFeaturedContentDefault,
    getTestimonialsContent: GetTestimonialsContentDefault,
    getNewsletterContent: GetNewsletterContentDefault,
    getContactFormContent: GetContactFormContentDefault,
    getCookiesPromptContent: GetCookiesPromptContentDefault,
    getWrongPagePromptContent: GetWrongPagePromptContentDefault,
    getUserSigninContent: GetUserSigninContentDefault,
    getUserSignupContent: GetUserSignupContentDefault,
    getUserSignoutContent: GetUserSignoutContentDefault,
    getUpdatePasswordContent: GetUpdatePasswordContentDefault,
    getResetPasswordContent: GetResetPasswordContentDefault,
    getUnsubscribeContent: GetUnsubscribeContentDefault,
    getUpdateSubscriberContent: GetUpdateSubscriberContentDefault
};
