name: Build, test and publish (master)

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    
    - name: Install dependencies
      run: | 
        npm install --global yarn
        yarn install

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: npx semantic-release

    - name: Display new release version number
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_major_version }}
        echo ${{ steps.semantic.outputs.new_release_minor_version }}
        echo ${{ steps.semantic.outputs.new_release_patch_version }}
    
    - name: Variable substitution appsettings file for Staging (NET Core)
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ github.workspace }}/TokanPages/appsettings.Staging.json
      env:
        AzureStorage.BaseUrl: "${{ secrets.AZURESTORAGE__BASEURL_TEST }}"
        AzureStorage.ContainerName: "${{ secrets.AZURESTORAGE__CONTAINERNAME_TEST }}"
        AzureStorage.ConnectionString: "${{ secrets.AZURESTORAGE__CONNECTIONSTRING }}"
        Sentry.Dsn: "${{ secrets.SENTRY__DSN_TEST }}"
        ConnectionStrings.DbConnectTest: "${{ secrets.CONNECTIONSTRING__TEST }}"
        SmtpServer.Account: "${{ secrets.SMTPSERVER__ACCOUNT }}"
        SmtpServer.Password: "${{ secrets.SMTPSERVER__PASSWORD }}"
        SmtpServer.Port: "${{ secrets.SMTPSERVER__PORT }}"
        SmtpServer.Server: "${{ secrets.SMTPSERVER__SERVER }}"

    - name: Variable substitution appsettings file for Production (NET Core)
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ github.workspace }}/TokanPages/appsettings.Production.json
      env:
        AppUrls.UpdateSubscriberPath: "${{ secrets.APPURLS__UPDATESUBSCRIBERPATH}}"
        AppUrls.UnsubscribePath: "${{ secrets.APPURLS__UNSUBSCRIBEPATH}}"
        AppUrls.DevelopmentOrigin: "${{ secrets.APPURLS__DEVELOPMENTORIGIN }}"
        AppUrls.DeploymentOrigin: "${{ secrets.APPURLS__DEPLOYMENTORIGIN }}"
        AzureStorage.BaseUrl: "${{ secrets.AZURESTORAGE__BASEURL }}"
        AzureStorage.ContainerName: "${{ secrets.AZURESTORAGE__CONTAINERNAME }}"
        AzureStorage.ConnectionString: "${{ secrets.AZURESTORAGE__CONNECTIONSTRING }}"
        Sentry.Dsn: "${{ secrets.SENTRY__DSN }}"
        ConnectionStrings.DbConnect: "${{ secrets.CONNECTIONSTRING__PROD }}"
        SmtpServer.Account: "${{ secrets.SMTPSERVER__ACCOUNT }}"
        SmtpServer.Password: "${{ secrets.SMTPSERVER__PASSWORD }}"
        SmtpServer.Port: "${{ secrets.SMTPSERVER__PORT }}"
        SmtpServer.Server: "${{ secrets.SMTPSERVER__SERVER }}"

    - name: Build and push Docker image (runs frontend & backend tests)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tokanpages
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}:${{ github.sha }}
