name: Build, test and publish (stage)

on:
  push:
    branches: [ stage ]

jobs:

  frontend-staging:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2.2.0

    - name: Staging | Build Docker (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Build Docker (execute with tests)
      run: |
        cd $PWD/TokanPages.ClientApp
        APP_VERSION="0.0.1-staging"
        BUILD_TIMESTAMP=$(date +"%Y-%m-%d at %T")
        docker build . \
        --build-arg "API_VERSION=${{ secrets.API_VERSION }}" \
        --build-arg "APP_VERSION=$APP_VERSION" \
        --build-arg "APP_DATE_TIME=$BUILD_TIMESTAMP" \
        --build-arg "APP_FRONTEND=${{ secrets.APP_FRONTEND_STAGING }}" \
        --build-arg "APP_BACKEND=${{ secrets.APP_BACKEND_STAGING }}" \
        --build-arg "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS_STAGING }}" \
        -t ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:frontend-staging-${{ github.sha }}

    - name: Staging | Push Docker image (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Push Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:frontend-staging-${{ github.sha }}

    # NOTE: due to a budget constraints, we use separate Azure App Service for staging slots. 
    # Microsoft Azure pricing tiers B1, B2 and B3 do not allow separate slots.
    - name: Staging | Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tokanpages-staging
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PROFILE_FE_STAGE }}
        images: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:frontend-staging-${{ github.sha }}

  backend-staging:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2.2.0
    
    - name: Variable substitution appsettings file for Staging (.NET)
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ github.workspace }}/TokanPages.Configuration/appsettings.Staging.json
      env:
        Email_PrivateKey: "${{ secrets.STAGE_EMAIL_PRIVATEKEY }}"
        Email_BaseUrl: "${{ secrets.STAGE_EMAIL_BASEURL }}"
        Email_Address_Admin: "${{ secrets.STAGE_EMAIL_ADDRESSES_ADMIN }}"
        Email_Address_Contact: "${{ secrets.STAGE_EMAIL_ADDRESSES_CONTACT }}"
        Email_Address_Support: "${{ secrets.STAGE_EMAIL_ADDRESSES_ITSUPPORT }}"
        Db_DatabaseContext: "${{ secrets.STAGE_DBCONNECT }}"
        Db_DatabaseContext_Migrator: "${{ secrets.STAGE_DBMIGRATOR }}"
        AZ_Storage_BaseUrl: "${{ secrets.STAGE_AZSTORAGE_BASEURL }}"
        AZ_Storage_ContainerName: "${{ secrets.STAGE_AZSTORAGE_CONTAINERNAME }}"
        AZ_Storage_ConnectionString: "${{ secrets.STAGE_AZSTORAGE_CONNECTIONSTRING }}"
        AZ_Storage_MaxFileSizeUserMedia: "${{ secrets.STAGE_AZSTORAGE_MAXFILESIZEUSERMEDIA }}"
        AZ_Storage_MaxFileSizeSingleAsset: "${{ secrets.STAGE_AZSTORAGE_MAXFILESIZESINGLEASSET }}"
        AZ_Redis_InstanceName: "${{ secrets.STAGE_AZREDIS_INSTANCENAME }}"
        AZ_Redis_ConnectionString: "${{ secrets.STAGE_AZREDIS_CONNECTIONSTRING }}"
        AZ_Redis_ExpirationMinute: "${{ secrets.STAGE_AZREDIS_EXPIRATIONMINUTE }}"
        AZ_Redis_ExpirationSecond: "${{ secrets.STAGE_AZREDIS_EXPIRATIONSECOND }}"
        Paths_UpdateSubscriber: "${{ secrets.STAGE_PATHS_UPDATESUBSCRIBER }}"
        Paths_Unsubscribe: "${{ secrets.STAGE_PATHS_UNSUBSCRIBE }}"
        Paths_UpdatePassword: "${{ secrets.STAGE_PATHS_UPDATEPASSWORD }}"
        Paths_Activation: "${{ secrets.STAGE_PATHS_ACTIVATION }}"
        Paths_DevelopmentOrigin: "${{ secrets.STAGE_PATHS_DEVELOPMENTORIGIN }}"
        Paths_DeploymentOrigin: "${{ secrets.STAGE_PATHS_DEPLOYMENTORIGIN }}"
        Paths_Templates_Newsletter: "${{ secrets.STAGE_PATHS_NEWSLETTER }}"
        Paths_Templates_ContactForm: "${{ secrets.STAGE_PATHS_CONTACTFORM }}"
        Paths_Templates_ResetPassword: "${{ secrets.STAGE_PATHS_RESETPASSWORD }}"
        Paths_Templates_RegisterForm: "${{ secrets.STAGE_PATHS_REGISTERFORM }}"
        Ids_Issuer: "${{ secrets.STAGE_IDS_ISSUER }}"
        Ids_Audience: "${{ secrets.STAGE_IDS_AUDIENCE }}"
        Ids_WebSecret: "${{ secrets.STAGE_IDS_WEBSECRET }}"
        Ids_RequireHttps: "${{ secrets.STAGE_IDS_REQUIREHTTPS }}"
        Ids_WebToken_Maturity: "${{ secrets.STAGE_IDS_WEBTOKEN_MATURITY }}"
        Ids_RefreshToken_Maturity: "${{ secrets.STAGE_IDS_REFRESHTOKEN_MATURITY }}"
        Limit_Reset_Maturity: "${{ secrets.STAGE_LIMITS_RESET_MATURITY }}"
        Limit_Activation_Maturity: "${{ secrets.STAGE_LIMITS_ACTIVATION_MATURITY }}"
        Limit_Likes_Anonymous: "${{ secrets.STAGE_LIMITS_LIKES_ANONYMOUS }}"
        Limit_Likes_User: "${{ secrets.STAGE_LIMITS_LIKES_USER }}"

    - name: Staging | Build Docker (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Build Docker (execute with tests)
      run: |
        docker build . \
        --build-arg "ENV_VALUE=Staging" \
        -t ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:backend-staging-${{ github.sha }}

    - name: Staging | Push Docker image (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Push Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:backend-staging-${{ github.sha }}

    # NOTE: due to a budget constraints, we use separate Azure App Service for staging slots. 
    # Microsoft Azure pricing tiers B1, B2 and B3 do not allow separate slots.
    - name: Staging | Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tokanpages-backend-staging
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PROFILE_BE_STAGE }}
        images: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:backend-staging-${{ github.sha }}
