name: Build, test and publish (stage)

on:
  push:
    branches: [ stage ]

jobs:

  frontend-staging:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Staging | Build Docker (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Build Docker (execute with tests)
      run: |
        cd $PWD/TokanPages.ClientApp
        APP_VERSION="0.0.1-staging"
        BUILD_TIMESTAMP=$(date +"%Y-%m-%d at %T")
        docker build . \
        --build-arg "API_VERSION=${{ secrets.API_VERSION }}" \
        --build-arg "APP_VERSION=$APP_VERSION" \
        --build-arg "APP_DATE_TIME=$BUILD_TIMESTAMP" \
        --build-arg "APP_FRONTEND=${{ secrets.APP_FRONTEND_STAGING }}" \
        --build-arg "APP_BACKEND=${{ secrets.APP_BACKEND_STAGING }}" \
        --build-arg "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS_STAGING }}" \
        -t ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:frontend-staging-${{ github.sha }}

    - name: Staging | Push Docker image (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Push Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:frontend-staging-${{ github.sha }}

    # NOTE: due to a budget constraints, we use separate Azure App Service for staging slots. 
    # Microsoft Azure pricing tiers B1, B2 and B3 do not allow separate slots.
    - name: Staging | Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tokanpages-staging
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PROFILE_FE_STAGE }}
        images: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:frontend-staging-${{ github.sha }}

  backend-staging:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log to Azure Cloud
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Azure Key Vault secrets
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.AZURE_KEY_VAULT }}
        secrets: ${{ secrets.AZURE_KEY_VAULT_LIST }}
      id: vault

    - name: Variable substitution appsettings file for Staging (.NET)
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ github.workspace }}/TokanPages.Configuration/appsettings.Staging.json
      env:
        Email_PrivateKey: "${{ steps.vault.outputs.StageEmailPrivateKey }}"
        Email_BaseUrl: "${{ steps.vault.outputs.StageEmailBaseUrl }}"
        Email_Address_Admin: "${{ steps.vault.outputs.StageEmailAddressesAdmin }}"
        Email_Address_Contact: "${{ steps.vault.outputs.StageEmailAddressesContact }}"
        Email_Address_Support: "${{ steps.vault.outputs.StageEmailAddressesItSupport }}"
        Db_DatabaseContext: "${{ steps.vault.outputs.StageDbConnect }}"
        Db_DatabaseContext_Migrator: "${{ steps.vault.outputs.StageDbMigrator }}"
        AZ_Storage_BaseUrl: "${{ steps.vault.outputs.StageAzStorageBaseUrl }}"
        AZ_Storage_ContainerName: "${{ steps.vault.outputs.StageAzStorageContainerName }}"
        AZ_Storage_ConnectionString: "${{ steps.vault.outputs.StageAzStorageConnectionString }}"
        AZ_Storage_MaxFileSizeUserMedia: "${{ steps.vault.outputs.StageAzStorageMaxFileSizeUserMedia }}"
        AZ_Storage_MaxFileSizeSingleAsset: "${{ steps.vault.outputs.StageAzStorageMaxFileSizeSingleAsset }}"
        AZ_Redis_InstanceName: "${{ steps.vault.outputs.StageAzRedisInstanceName }}"
        AZ_Redis_ConnectionString: "${{ steps.vault.outputs.StageAzRedisConnectionString }}"
        AZ_Redis_ExpirationMinute: "${{ steps.vault.outputs.StageAzRedisExpirationMinute }}"
        AZ_Redis_ExpirationSecond: "${{ steps.vault.outputs.StageAzRedisExpirationSecond }}"
        Paths_UpdateSubscriber: "${{ steps.vault.outputs.StagePathsUpdateSubscriber }}"
        Paths_Unsubscribe: "${{ steps.vault.outputs.StagePathsUnsubscribe }}"
        Paths_UpdatePassword: "${{ steps.vault.outputs.StagePathsUpdatePassword }}"
        Paths_Activation: "${{ steps.vault.outputs.StagePathsActivation }}"
        Paths_DevelopmentOrigin: "${{ steps.vault.outputs.StagePathsDevelopmentOrigin }}"
        Paths_DeploymentOrigin: "${{ steps.vault.outputs.StagePathsDeploymentOrigin }}"
        Paths_Templates_Newsletter: "${{ steps.vault.outputs.StagePathsNewsletter }}"
        Paths_Templates_ContactForm: "${{ steps.vault.outputs.StagePathsContactForm }}"
        Paths_Templates_ResetPassword: "${{ steps.vault.outputs.StagePathsResetPassword }}"
        Paths_Templates_RegisterForm: "${{ steps.vault.outputs.StagePathsRegisterForm }}"
        Ids_Issuer: "${{ steps.vault.outputs.StageIdsIssuer }}"
        Ids_Audience: "${{ steps.vault.outputs.StageIdsAudience }}"
        Ids_WebSecret: "${{ steps.vault.outputs.StageIdsWebSecret }}"
        Ids_RequireHttps: "${{ steps.vault.outputs.StageIdsRequireHttps }}"
        Ids_WebToken_Maturity: "${{ steps.vault.outputs.StageIdsWebTokenMaturity }}"
        Ids_RefreshToken_Maturity: "${{ steps.vault.outputs.StageIdsRefreshTokenMaturity }}"
        Limit_Reset_Maturity: "${{ steps.vault.outputs.StageLimitsResetMaturity }}"
        Limit_Activation_Maturity: "${{ steps.vault.outputs.StageLimitsActivationMaturity }}"
        Limit_Likes_Anonymous: "${{ steps.vault.outputs.StageLimitsLikesAnonymous }}"
        Limit_Likes_User: "${{ steps.vault.outputs.StageLimitsLikesUser }}"

    - name: Staging | Build Docker (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Build Docker (execute with tests)
      run: |
        docker build . \
        --build-arg "ENV_VALUE=Staging" \
        -t ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:backend-staging-${{ github.sha }}

    - name: Staging | Push Docker image (prepare)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

    - name: Staging | Push Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:backend-staging-${{ github.sha }}

    # NOTE: due to a budget constraints, we use separate Azure App Service for staging slots. 
    # Microsoft Azure pricing tiers B1, B2 and B3 do not allow separate slots.
    - name: Staging | Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tokanpages-backend-staging
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PROFILE_BE_STAGE }}
        images: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}:backend-staging-${{ github.sha }}
